spring.application.name=M8Shopping

#Database config
spring.datasource.url=jdbc:h2:file:./db/db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=Manimahesh8
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#set up local H2 database console
spring.h2.console.enabled=true
spring.h2.console.path=/db-console
spring.h2.console.settings.web-allow-others=false

#local h2 tables setup on startup; use the value none in production!
spring.jpa.hibernate.ddl-auto=create-drop

#Logging setting
logging.level.com.m8.shopping = DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.name=appLog.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#Multipart enabling
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mvc.static-path-pattern=/resources/static/**

